version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=timescale
      - POSTGRES_PASSWORD=timescale_pass
      - POSTGRES_DB=timescaledb
    volumes:
      - tsdata:/var/lib/postgresql/data
      - ./docker/timescaledb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timescale -d timescaledb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tsdata:
